name: Reproduce Bug
on:
  workflow_dispatch:

jobs:
  # This will always fail.
  install-311:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

  # This will pass on the -full containers, but not on the standard ones.
  install-37:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
